name: compress

on:
  push:
    paths: '**.ttf'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - run: |
          fonttools ttLib.woff2 compress DosKor.ttf
          fonttools ttLib.woff2 compress WinKor.ttf
