name: compress

on:
  push:
    paths: '**.ttf'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - run: |
          pip install fonttools[woff]
          fonttools ttLib.woff2 compress DosKor.ttf
          fonttools ttLib.woff2 compress WinKor.ttf
      - uses: stefanzweifel/git-auto-commit-action@v4
